<?php
module_load_include('inc', 'tvdb_search', 'tvdb_search.search_functions');
/*
* Implements hook_permission()
*/
function tvdb_search_permission() {
    $permissions['administer tvdb search'] = array(
            'title' => t('Administer TVDB Search'),
            'description' => t('Perform administration tasks for TVDB Search module.'),
        );
    return $permissions;
}

/*
* Implements hook_menu()
*/
function tvdb_search_menu() {
    $items = array();
    $items['admin/config/tvdb_search'] = array(
            'title' => 'TVDB Search Settings',
            'type' => MENU_NORMAL_ITEM,
            'page callback' => 'drupal_get_form',
            'page arguments' => array('tvdb_search_config_form'),
            'access arguments' => array('administer tvdb search'),
        );
    $items['tvdb_search'] = array(
            'title' => 'TVDB Search',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => TRUE,
            'page callback' => 'drupal_get_form',
            'page arguments' => array('tvdb_search_form'),
            'menu_name' => 'main-menu',
        );
    $items['tvdb_login'] = array(
            'title' => 'TVDB Login',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => TRUE,
            'page callback' => 'tvdb_login',
            'menu_name' => 'main-menu',
        );
    $items['tvdb_search/%/results'] = array(
            'title' => 'TVDB Search Results',
            'type' => MENU_CALLBACK,
            'access callback' => TRUE,
            'page callback' => 'tvdb_search_results_display_page',
            'page arguments' => array(1),
        );
    return $items;
}

/*
* TVDB Search form
*/
function tvdb_search_form($form, &$form_state) {
    $form['tvdb_search_search_term'] = array(
            '#type' => 'textfield',
            '#title' => t('Search TVDB'),
            '#description' => t('Enter the title of a TV series to search for.'),
        );
    $form['tvdb_search_submit'] = array(
            '#type' => 'submit',
            '#value' => t('Search'),
        );
    return $form;
}

function tvdb_search_results_display_page($search_term) {
    $href = variable_get('tvdb_search_link_href', '');
    $link_text = variable_get('tvdb_search_link_text', '');
    $results = tvdb_search($search_term);
    $link = '';
    if ($href && $link_text) {
    }
    dpm($results);
    $search_form = drupal_get_form('tvdb_search_form');
    $string = '';
    $string .= drupal_render($search_form);
    $string .= '<h2>Results of search for "' . $search_term . '":</h2>';
    foreach($results->data as $show) {
        $string .= "<h3>Show Title: " . $show->seriesName . "</h3>";
        $string .= "<p>Overview: " . $show->overview . "</p>";
        $string .= "<p>Network: " . $show->network . "</p>";
        $string .= "<p>Status: " . $show->status . "</p>";
        $link = l($link_text, $href . '/' . $show->id . '/' . $show->seriesName, array(
            'html' => TRUE,
        ));
        $string .= $link;
        $string .= "<hr>";
    }
    return $string;
}

/*
*
*/
function tvdb_search_form_submit($form, &$form_state) {
    $search_term = $form_state['values']['tvdb_search_search_term'];
    $form_state['redirect'] = 'tvdb_search/' . $search_term . '/results';
}

/*
* Administration form
*/
function tvdb_search_config_form($form, &$form_state) {
    $form['tvdb_search_apikey'] = array(
            '#type' => 'textfield',
            '#title' => t('TVDB Api Key'),
            '#default_value' => variable_get('tvdb_search_apikey', ''),
        );
    $form['tvdb_search_username'] = array(
            '#type' => 'textfield',
            '#title' => t('TVDB Username'),
            '#default_value' => variable_get('tvdb_search_username', ''),
        );
    $form['tvdb_search_userkey'] = array(
            '#type' => 'textfield',
            '#title' => t('TVDB Userkey'),
            '#default_value' => variable_get('tvdb_search_userkey', ''),
        );
    $form['tvdb_search_token'] = array(
            '#type' => 'textfield',
            '#title' => t('TVDB Token'),
            '#default_value' => variable_get('tvdb_search_token', ''),
            '#disabled' => TRUE,
        );
    $form['tvdb_search_link_text'] = array(
            '#type' => 'textfield',
            '#title' => t('Link Text'),
            '#description' => t('This will be the link text of the link that is attached to each found show.'),
            '#default_value' => variable_get('tvdb_search_link_text', ''),
        );
    $form['tvdb_search_link_href'] = array(
            '#type' => 'textfield',
            '#title' => t('Link HREF'),
            '#description' => t('This is the path that the link will lead to.'),
            '#default_value' => variable_get('tvdb_search_link_href', ''),
        );
    return system_settings_form($form);
}
