<?php

/*
* Implements hook_permission()
*/
function email_reminders_permission() {
    $permissions['administer email reminders'] = array(
            'title' => t('Administer Email Reminders'),
            'description' => t('Perform administration tasks for Email Reminders module.'),
        );
    return $permissions;
}

/*
* Implements hook_menu()
*/
function email_reminders_menu() {
    $items = array();
    $items['admin/config/email_reminders'] = array(
            'title' => 'Email Reminder Settings',
            'type' => MENU_NORMAL_ITEM,
            'page callback' => 'drupal_get_form',
            'page arguments' => array('email_reminders_config_form'),
            'access arguments' => array('administer email reminders'),
        );
    return $items;
}

/*
* Administration form for Email Reminders module
*/
function email_reminders_config_form($form, &$form_state) {
    $form['email_reminders_enable'] = array(
            '#type' => 'checkbox',
            '#title' => t('Enable Email Reminders'),
            '#default_value' => variable_get('email_reminders_enable', 0),
        );
    $form['email_reminders_send_from'] = array(
            '#type' => 'textfield',
            '#title' => t('Send From Email Address'),
            '#description' => t('Email address that will be used to send the reminders.'),
            '#default_value' => variable_get('email_reminders_send_from', ''),
        );
    return system_settings_form($form);
}
